# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    command: postgres -c log_statement=all -c log_destination=stderr
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
